name: Tests

on:
  push:
    branches: ["master"]
    paths:
      - "src/**"
      - "examples/**"
      - "templates/**"
      - "tests/**"
      - "tests_adapters/**"
      - "utils/**"
  pull_request:
    branches: ["master", "develop"]
    paths:
      - "src/**"
      - "examples/**"
      - "templates/**"
      - "tests/**"
      - "tests_adapters/**"
      - "utils/**"
  workflow_dispatch:

jobs:
  check_code_quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}
      - name: Install
        run: |
          pip install torch==1.12.1
          pip install .[quality]
      - name: Check Quality and Repo Consistency
        run: |
          make quality
          make repo-consistency
  test_adapter_methods:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install
        run: |
          pip install torch==1.12.1
          pip install .[sklearn,testing,sentencepiece,vision]
          pip install datasets
      - name: Test
        run: |
          make test-adapter-methods
  test_adapter_models:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install
        run: |
          pip install torch==1.12.1
          pip install .[sklearn,testing,sentencepiece,vision]
          pip install datasets
      - name: Test
        run: |
          make test-adapter-models
