MODEL:
  BACKBONE: bert-base-uncased
  PATH: /mnt/data/oss_beijing/liuhongyi/models/bert-base-uncased
  
ADAPTER:
  TRAIN: None
  EVAL: None

DATA:
  SRC_DATASET: None
  TGT_DATASET: chemdner
  GRANULARITY: sent

TRAIN:
  TGT_EPOCHS: 50
  BATCH_SIZE: 32
  LR: 0.00005
  ORACLE: True
  TWO_STAGE: False

EVAL:
  OVERWRITE: True
  BATCH_SIZE: 128

LOSSES:
  NAME: CrossEntropy

OUTPUT:
  ADAPTER_SAVE_DIR: adapter/sent
  HEAD_SAVE_DIR: head/sent
  RESULT_SAVE_DIR: results/sent