MODEL:
  BACKBONE: bert-base-uncased
  PATH: /root/autodl-tmp/models/DAPT_drugprot
  
ADAPTER:
  TRAIN: None
  EVAL: None

DATA:
  TGT_DATASET: drugprot
  GRANULARITY: para

TRAIN:
  TGT_EPOCHS: 80
  BATCH_SIZE: 16
  LR: 0.0001
  ORACLE: False
  TWO_STAGE: False

EVAL:
  OVERWRITE: True
  BATCH_SIZE: 128

TGT_LOSS:
  NAME: CrossEntropy

OUTPUT:
  ADAPTER_SAVE_DIR: adapter/para/fs/dapt
  HEAD_SAVE_DIR: head/para/fs/dapt
  RESULT_SAVE_DIR: results/para/fs/dapt