MODEL:
  BACKBONE: bert-base-uncased
  PATH: PATH_TO_BERT
  
ADAPTER:
  TRAIN: None
  EVAL: None
  ENABLE: True

DATA:
  TGT_DATASET: chemdner
  GRANULARITY: para

TRAIN:
  TGT_EPOCHS: 80
  BATCH_SIZE: 16
  LR: 0.0001
  ORACLE: False
  TWO_STAGE: False

EVAL:
  OVERWRITE: True
  BATCH_SIZE: 128

TGT_LOSS:
  NAME: CrossEntropy

OUTPUT:
  ADAPTER_SAVE_DIR: adapter/para/fs
  HEAD_SAVE_DIR: head/para/fs
  RESULT_SAVE_DIR: results/para/fs