MODEL:
  BACKBONE: bert-base-uncased
  PATH: /root/autodl-tmp/models/bert-base-uncased
  
ADAPTER:
  TRAIN: None
  EVAL: biomedical_ner_bert-base-uncased_inter

HEAD:
  EVAL: biomedical_ner_bert-base-uncased_head_inter

DATA:
  TGT_DATASET: biomedical
  BIOMEDICAL:
    SIM_METHOD: None
  GRANULARITY: para

TRAIN:
  SRC_EPOCHS: 100
  TGT_EPOCHS: 80
  SRC_BATCH_SIZE: 64
  BATCH_SIZE: 16
  SRC_LR: 0.0001
  LR: 0.0001
  ORACLE: False
  TWO_STAGE: False
  SEED: 42

EVAL:
  OVERWRITE: True
  BATCH_SIZE: 128

TGT_LOSS:
  NAME: CrossEntropy

OUTPUT:
  ADAPTER_SAVE_DIR: adapter/para/tl/biomedical
  HEAD_SAVE_DIR: head/para/tl/biomedical
  RESULT_SAVE_DIR: results/para/tl/biomedical