MODEL:
  BACKBONE: bert-base-uncased
  PATH: /mnt/data/oss_beijing/liuhongyi/models/bert-base-uncased
  
ADAPTER:
  TRAIN: None
  EVAL: None

DATA:
  SRC_DATASET: None
  TGT_DATASET: chemdner
  GRANULARITY: para

TRAIN:
  TGT_EPOCHS: 80
  BATCH_SIZE: 16
  LR: 0.0001
  ORACLE: False
  TWO_STAGE: False

EVAL:
  OVERWRITE: True
  BATCH_SIZE: 128

TGT_LOSS:
  NAME: CrossEntropy

OUTPUT:
  ADAPTER_SAVE_DIR: adapter/para/fs/None/chemdner
  HEAD_SAVE_DIR: head/para/fs/None/chemdner
  RESULT_SAVE_DIR: results/para/fs/None/chemdner