MODEL:
  BACKBONE: BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext
  PATH: /mnt/data/oss_beijing/liuhongyi/models/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext
  
ADAPTER:
  TRAIN: None
  EVAL: None

DATA:
  SRC_DATASET: None
  TGT_DATASET: chemdner
  GRANULARITY: para

TRAIN:
  TGT_EPOCHS: 50
  BATCH_SIZE: 32
  LR: 0.00005
  ORACLE: True
  TWO_STAGE: False

EVAL:
  OVERWRITE: True
  BATCH_SIZE: 128

LOSSES:
  NAME: CrossEntropy

OUTPUT:
  ADAPTER_SAVE_DIR: adapter/para
  HEAD_SAVE_DIR: head/para
  RESULT_SAVE_DIR: results/para