MODEL:
  BACKBONE: bert-base-uncased
  PATH: /mnt/data/oss_beijing/liuhongyi/models/bert-base-uncased
  
ADAPTER:
  TRAIN: adapter/para/tl/biomedical/biomedical_ner_bert-base-uncased_inter
  EVAL: biomedical_ner_bert-base-uncased

DATA:
  SRC_DATASET: tl
  TGT_DATASET: biomedical
  GRANULARITY: para

TRAIN:
  TGT_EPOCHS: 120
  BATCH_SIZE: 64
  LR: 0.0001
  ORACLE: False
  TWO_STAGE: False

EVAL:
  OVERWRITE: True
  BATCH_SIZE: 128

SRC_LOSS:
  NAME: CrossEntropy

TGT_LOSS:
  NAME: CrossEntropy

OUTPUT:
  ADAPTER_SAVE_DIR: adapter/para/tl/biomedical
  HEAD_SAVE_DIR: head/para/tl/biomedical
  RESULT_SAVE_DIR: results/para/tl/biomedical