MODEL:
  BACKBONE: bert-base-uncased
  PATH: /mnt/data/oss_beijing/liuhongyi/models/bert-base-uncased
  
ADAPTER:
  TRAIN: None
  EVAL: politics_ner_bert-base-uncased

DATA:
  SRC_DATASET: crossner
  TGT_DATASET: politics
  GRANULARITY: para

TRAIN:
  TGT_EPOCHS: 100
  BATCH_SIZE: 64
  LR: 0.0001
  ORACLE: False
  TWO_STAGE: False

EVAL:
  OVERWRITE: True
  BATCH_SIZE: 128

TGT_LOSS:
  NAME: CrossEntropy

OUTPUT:
  ADAPTER_SAVE_DIR: adapter/para/crossner/politics
  HEAD_SAVE_DIR: head/para/crossner/politics
  RESULT_SAVE_DIR: results/para/crossner/politics